networking: false
f5workshop: false
admin_password: ansible
workshop_dns_zone: "rhdemo.io"
storage_state: "present"
teardown: false
towerinstall: false
website_information: ""
dns_information: "No errors with DNS"
